# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=80)),
                ('video_file', models.FileField(upload_to='videos')),
                ('image_title', models.CharField(max_length=80)),
                ('image_file', models.FileField(upload_to='images')),
                ('status', models.IntegerField(db_index=True)),
                ('callback_url', models.URLField()),
            ],
        ),
    ]
